baseURL: 'https://2021.ubucon.asia/'
languageCode: en-us
title: Ubucon Asia 2021
theme: ubuconasia
Paginate: 5
buildFuture: true
enableRobotsTXT: true

defaultContentLanguage: en
languages:
  ko:
    languageName: 한국어
    title: 우부콘 아시아 2021
    weight: 2
    params:
      description: >-
        아시아에 있는 다양한 우분투 지역 커뮤니티에서 준비한 첫 우분투 아시아 컨퍼런스.
      period: 2021년 9월 25일 ~ 26일
    menu:
      main:
        - identifier: about
          name: 소개
          url: about
          weight: 1
        - identifier: hosts
          name: 주최
          url: hosts
          weight: 2
        - identifier: programs-group
          name: 프로그램
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: 세션
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: 참여 확인된 세션
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: 후원사/개인후원
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: 후원사
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: 개인 후원자
          url: patrons
          weight: 4
        - identifier: news
          name: 소식
          url: news
          weight: 5
        - identifier: wiki
          name: 위키
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 6
  en:
    languageName: English
    title: Ubucon Asia 2021
    weight: 1
    params:
      description: >-
        The first Ubuntu Asia conference organized by Ubuntu Local Communities in Asia.
      period: September 25th ~ 26th, 2021 
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 1
        - identifier: hosts
          name: Hosts
          url: hosts
          weight: 2
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: Sessions
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Confirmed sessions
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 4
        - identifier: news
          name: News
          url: news
          weight: 5
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 6
  id:
    languageName: Bahasa Indonesia
    title: Ubucon Asia 2021
    weight: 2
    params:
      description: >-
        Konferensi Ubuntu Asia pertama yang diselenggarakan oleh Komunitas Lokal Ubuntu di Asia.
      period: 25~26 September, 2021
    menu:
      main:
        - identifier: about
          name: Tentang
          url: about
          weight: 1
        - identifier: hosts
          name: Host
          url: hosts
          weight: 2
        - identifier: programs-group
          name: Program
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: Sesi
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Sesi yang Dikonfirmasi
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: Sponsor/Patron
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsor
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Patron Individual
          url: patrons
          weight: 4
        - identifier: news
          name: Berita
          url: news
          weight: 5
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 6
  ja:
    languageName: 日本語
    title: Ubucon Asia 2021
    weight: 3
    params:
      description: >-
        アジアのUbuntuコミュニティが集結する、アジア地域初のUbuntuカンファレンス開催
      period: 2021年 第3〜4四半期に開催準備中
    menu:
      main:
        - identifier: about
          name: Ubucon Asiaとは
          url: about
          weight: 1
        - identifier: hosts
          name: Hosts
          url: hosts
          weight: 2
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: セッション
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Confirmed sessions
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: スポンサー/Patrons
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: スポンサー
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 4
        - identifier: news
          name: ニュース
          url: news
          weight: 4
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 5
  zh-hant-tw:
    languageName: 正體中文(臺灣)
    title: Ubucon Asia 2021
    weight: 2
    params:
      description: >-
        The first Ubuntu Asia conference organized by Ubuntu Local Communities in Asia.
      period: September 25th ~ 26th, 2021 
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 1
        - identifier: hosts
          name: Hosts
          url: hosts
          weight: 2
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: Sessions
          url: sessions
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Confirmed sessions
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 4
        - identifier: news
          name: News
          url: news
          weight: 5
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 6
params:
  contact: contact@ubucon.asia
  calendarOrganizer: Ubucon Asia 2021 Organizers
  calendarUidSuffix: 2021.asia.ubucon.org
  facebook: ubuconasia
  twitter: ubuconasia
  github: ubucon-asia
  repo: https://github.com/ubucon-asia/2021
  copyright:  >-
    © 2021 Ubucon Asia 2021 Website authors.
    Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY 4.0. 
    Ubuntu and Canonical are registered trademarks of Canonical Ltd.
  email: contact@ubucon.asia
  registerURLs:
    attendee: https://eventyay.com/e/75ac7f83
    callForSpeakers: /cfs
  timetable:
    dateStart: 2021-09-25T12:00:00+09:00
    dateEnd: 2021-09-26T22:00:00+09:00
    timeStart: 2000-01-01T13:00:00+09:00 # Use random date for timeStart param
outputs:
  section: ["HTML", "RSS", "Calendar"]
